export const LIST_COURIERS = [
  { label: "JNE Express", value: "jne" },
  { label: "POS Indonesia", value: "pos" },
  { label: "J&T Express", value: "jnt" },
  { label: "J&T Cargo", value: "jnt_cargo" },
  { label: "SiCepat", value: "sicepat" },
  { label: "TIKI", value: "tiki" },
  { label: "AnterAja", value: "anteraja" },
  { label: "Wahana", value: "wahana" },
  { label: "Ninja Express", value: "ninja" },
  { label: "Lion Parcel", value: "lion" },
  { label: "PCP Express", value: "pcp" },
  { label: "JET Express", value: "jet" },
  { label: "REX Express", value: "rex" },
  { label: "First Logistics", value: "first" },
  { label: "ID Express", value: "ide" },
  { label: "Shopee Express", value: "spx" },
  { label: "KGXpress", value: "kgx" },
  { label: "SAP Express", value: "sap" },
  { label: "JX Express", value: "jxe" },
  { label: "RPX", value: "rpx" },
  { label: "Kurir Rekomendasi", value: "kurir_tokopedia" },
  { label: "Lazada Express", value: "lex" },
  { label: "Indah Cargo", value: "indah_cargo" },
  { label: "ANT Cargo", value: "ant_cargo" },
  { label: "Next Logistik", value: "next_logistik" },
];
